'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ApiClient

    '''<summary>
    '''btnAllProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAllProducts As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvAllProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAllProducts As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tbProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbProductID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProductID As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProductID As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tbProductNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbProductNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbProductName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbProductDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbProductDescription As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPrice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbSubCategoryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSubCategoryID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbFeatured control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFeatured As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbMainCategoryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMainCategoryID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnCreateProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProduct As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbUpdateProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUpdateProductID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnUpdateProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateProduct As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbDeleteProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDeleteProductID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnDeleteProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteProductID As Global.System.Web.UI.WebControls.Button
End Class
